### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by sryu1** [ijkannan/777-300ER-for-flightgear#3]
It would be wayyyyy better to have The repo name as something like 777-300ER so that when you `git clone` it, you don't have to name it, same with just `git pull` anddd same with when you download the zip file and unzip it.

**Comment by sryu1** [comment]
Because I realised that both installation instructions don't work with the repo name like this... Is it also possible to remove the folder called 777 again?

**Comment by sryu1** [comment]
So that it looks like this https://github.com/sryu1/777-300
1. Repository name is 777-300 which flightgear can read as an aircraft folder name
2. Files are not in another subfolder called 777 so that after `git clone`, flightgear can run straight away (or after downoading zip and removing -master)

**Comment by sryu1** [comment]
@sriemmanuel787 @ijkannan Any thoughts? I can do a pull request for my current repo if you want, it's also got a little readme change...

**Comment by sryu1** [comment]
https://github.com/ijkannan/777-300-300ER-for-FlightGear/pull/4

**Comment by naviat-dev** [comment]
@sryu1 I have changed the name in unstable-dev, once @ijkannan deems it fit the branch will be merged
I will also change the read-me in that branch as well

**Comment by sryu1** [comment]
Wait, I didn't mean to change the folder name but change the repository name, the name "777-300-300ER-for-FlightGear" is a bit too long in my opinion. and since the folder is inside the folder right now, if you `git clone` this repo into a folder you point FlightGear to, it can't find it... So what I was suggesting was that:

GitHub repository name is 777-300 which is more simple, 
Files are not in another subfolder called 777-300 so that after `git clone`, flightgear can run the aircraft straight away instead of having to remove the main folder "called 777-300-300ER-for-FlightGear and doing everything manually (It's just a bit annoying)(or after downoading zip and removing -master)

**Comment by sryu1** [comment]
I'm not sure if what I'm saying right now makes sense...

**Comment by naviat-dev** [comment]
No, I definitely understand what you're saying, and I agree with you. However, since I.J. Kannan is the owner of the repository, he _has_ to be the one to make the changes. I can't do that.

**Comment by sryu1** [comment]
Ah, ok, I was just a bit confused, because in the unstable-dev branch, you changed the subfolder name instead of removing it.

**Comment by sryu1** [comment]
@ijkannan Would it be possible if you can move all files out of the subfolder so that flightgear can recognise that straight away after git clone?
