### ISSUE TITLE
Thumbnails and splash

### ISSUE THREAD

**Issue by sryu1** [ijkannan/777-300ER-for-flightgear#6]
I think we should create new ones...

**Comment by naviat-dev** [comment]
I think so too, but here's the thing...
As a livery developer, I think that the current UV map for the 777 is fit for the rubbish heap, so I'm going to make a new one and create new liveries for it as well. I hope to get those changes done relatively soon, and so I don't want to make new splash screens yet. If you have any good ones, send them to me and i can add them.

**Comment by sryu1** [comment]
Ah, ok.
